[package]
name = "killer-reader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.4"
serde = { version = "1.0", features = ["derive"] }
reqwest = "0.11.20"
chrono = "0.4.31"